
cuda is not avaiable.


============= Running time: 0th =============
Creating server and clients ...
Traceback (most recent call last):
  File "D:\Python\PycharmProjects\PFL-Non-IID-master\FedALA-main\FedALA-main\system\main.py", line 115, in <module>
    run(args)
  File "D:\Python\PycharmProjects\PFL-Non-IID-master\FedALA-main\FedALA-main\system\main.py", line 55, in run
    server = FedALA(args, i)
  File "D:\Python\PycharmProjects\PFL-Non-IID-master\FedALA-main\FedALA-main\system\flcore\servers\serverALA.py", line 35, in __init__
    self.set_clients(args, clientALA)
  File "D:\Python\PycharmProjects\PFL-Non-IID-master\FedALA-main\FedALA-main\system\flcore\servers\serverALA.py", line 75, in set_clients
    train_data = read_client_data(self.dataset, i, is_train=True)
  File "D:\Python\PycharmProjects\PFL-Non-IID-master\FedALA-main\FedALA-main\system\utils\data_utils.py", line 87, in read_client_data
    train_data = read_data(dataset, idx, is_train)
  File "D:\Python\PycharmProjects\PFL-Non-IID-master\FedALA-main\FedALA-main\system\utils\data_utils.py", line 67, in read_data
    with open(train_file, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../dataset\\Tiny-imagenet\\train/train0_.npz'
